// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjaCiZZ2wdBceHW5gny7Bvqv0jbwD94Tk',
    appId: '1:1026626013195:web:56d52e61fe0fd877ea9f0e',
    messagingSenderId: '1026626013195',
    projectId: 'ctsea1',
    authDomain: 'ctsea1.firebaseapp.com',
    storageBucket: 'ctsea1.appspot.com',
    measurementId: 'G-DJ1DQDE3EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXUGksZxY0OHZ8o_sVbknO-YK0HRpVu_w',
    appId: '1:1026626013195:android:007c1a0c44b3655bea9f0e',
    messagingSenderId: '1026626013195',
    projectId: 'ctsea1',
    storageBucket: 'ctsea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWLkRHnWY88_vRq2o6mICMIA4xDCUc2Vw',
    appId: '1:1026626013195:ios:f5c0799f54947310ea9f0e',
    messagingSenderId: '1026626013195',
    projectId: 'ctsea1',
    storageBucket: 'ctsea1.appspot.com',
    iosClientId: '1026626013195-pvn1tmnq68g76rq2ur9a1vjrtigtdsc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWLkRHnWY88_vRq2o6mICMIA4xDCUc2Vw',
    appId: '1:1026626013195:ios:f5c0799f54947310ea9f0e',
    messagingSenderId: '1026626013195',
    projectId: 'ctsea1',
    storageBucket: 'ctsea1.appspot.com',
    iosClientId: '1026626013195-pvn1tmnq68g76rq2ur9a1vjrtigtdsc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointment',
  );
}
